org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

modVersion=26.1.2-1.0.1
currentChangelog=- Added Cable Tiers compat

minecraftVersion=26.1.2
refinedarchitectVersion=1.7.1
refinedstorageVersion=3.2.1